#!/usr/bin/env python3
# Generate observed.txt: one 32-bit word per line, hex with '?' for unknown nibbles.
# Words are in order as generated by MT after seeding.

# Known private keys (K_n) for n=2..69 (already used in C++ code).
K_small = {
    2: 3, 3: 7, 4: 8, 5: 21, 6: 49, 7: 76, 8: 224,
    9: 467, 10: 514, 11: 1155, 12: 2683, 13: 5216, 14: 10544,
    15: 26867, 16: 51510, 17: 95823, 18: 198669, 19: 357535,
    20: 863317, 21: 1811764, 22: 3007503, 23: 5598802, 24: 14428676,
    25: 33185509, 26: 54538862, 27: 111949941, 28: 227634408,
    29: 400708894, 30: 1033162084, 31: 2102388551, 32: 3093472814,
    33: 7137437912, 34: 14133072157, 35: 20112871792, 36: 42387769980,
    37: 100251560595, 38: 146971536592, 39: 323724968937, 40: 1003651412950,
    41: 1458252205147, 42: 2895374552463, 43: 7409811047825, 44: 15404761757071,
    45: 19996463086597, 46: 51408670348612, 47: 119666659114170, 48: 191206974700443,
    49: 409118905032525, 50: 611140496167764, 51: 2058769515153876, 52: 4216495639600700,
    53: 6763683971478124, 54: 9974455244496707, 55: 30045390491869460, 56: 44218742292676575,
    57: 138245758910846492, 58: 199976667976342049, 59: 525070384258266191, 60: 1135041350219496382,
    61: 1425787542618654982, 62: 3908372542507822062, 63: 8993229949524469768, 64: 17799667357578236628,
    65: 30568377312064202855
}
# For n=66..69, hex strings
K_big = {
    66: "2832ed74f2b5e35ee",
    67: "730fc235c1942c1ae",
    68: "bebb3940cd0fc1491",
    69: "101d83275fb2bc7e0c"
}

# Compute L_n = K_n - 2^(n-1) as 256-bit integer, return as int.
def compute_L(n):
    if n <= 65:
        K = K_small[n]
        start = 1 << (n-1)
        L = K - start
    else:
        K_hex = K_big[n]
        K = int(K_hex, 16)
        start = 1 << (n-1)
        L = K - start
    return L

# For each puzzle n, we have a 256-bit value d_n (unknown) which is the concatenation of
# 8 words: w0 w1 w2 w3 w4 w5 w6 w7 (w0 most significant). The lower k = n-1 bits of this
# value equal L. We'll split this into known bits per word.
# Word index offset: puzzle 1 uses words 0..7, puzzle 2 uses 8..15, ... puzzle n uses
# base = (n-1)*8 .. base+7.
# We'll create a dictionary mapping global word index -> bytearray of known bits (32 bits).
# Initially all bits unknown. We'll fill in known bits from each L.

words = {}  # global index -> list of 32 chars ('0','1','?')

def set_known_bits(global_word_idx, bit_start_within_word, length, value_bits):
    # value_bits is a string of length 'length' (LSB first) to be placed at bit_start within word
    if global_word_idx not in words:
        words[global_word_idx] = ['?'] * 32
    w = words[global_word_idx]
    for i in range(length):
        w[bit_start_within_word + i] = value_bits[i]

# Process puzzles 2..69
for n in range(2, 70):
    L = compute_L(n)
    k = n - 1   # number of known lower bits of the 256-bit value
    # Convert L to bits (LSB first)
    L_bits = bin(L)[2:].zfill(k)[::-1]  # string of length k, LSB first
    # Determine which words are affected, and set bits
    base = (n-1) * 8
    # The 256-bit number: word indices base+0..base+7, with base+7 being the least significant.
    # The lower k bits cover bits from 0..k-1 of the 256-bit value.
    # We'll map these bit positions to words and bit positions within words.
    for bit_pos in range(k):
        # which word? word index = base + 7 - (bit_pos // 32)
        word_offset = 7 - (bit_pos // 32)
        word_idx = base + word_offset
        bit_in_word = bit_pos % 32
        # set the bit
        if word_idx not in words:
            words[word_idx] = ['?'] * 32
        words[word_idx][bit_in_word] = L_bits[bit_pos]

# Now we have words dict with partial bits. We need to output words in order from 0 to max index.
max_idx = max(words.keys()) if words else 0
target = 999  # ensure at least 625 words (0..624)
with open('observed.txt', 'w') as f:
    for idx in range(target + 1):
        if idx in words:
            bits = words[idx]
            hex_str = ''
            for nibble in range(8):
                nibble_bits = bits[nibble*4 : nibble*4+4]
                if all(b == '?' for b in nibble_bits):
                    hex_str += '?'
                elif all(b != '?' for b in nibble_bits):
                    val = int(''.join(bits[i] for i in range(nibble*4, nibble*4+4)), 2)
                    hex_str += f'{val:X}'
                else:
                    hex_str += '?'
            f.write(hex_str + '\n')
        else:
            f.write('????????\n')

print(f"Generated observed.txt with {target + 1} words.")